name: "Master Docs Publication"
on:
  release:
    types: created

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install poetry
          poetry install
      - name: Directly build docs
        run: |
          pip install -r docs/requirements.txt
          sphinx-build docs/source ./docs/build/html/
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
